version: 1

builder:
  configs:
    - documentation_targets: [MediaBridge]
      swift_version: 6.0

previewReleases: []

generationParameters:
  minimumSwiftVersion: 6.0
  minPlatformVersions:
    iOS: "15.0"
